name: calpop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - pandas
  - openpyxl
  - python-multipart
  - cryptography
  - pytest
  - httpx
  - pip
  - pip:
    - python-jose[cryptography]
    - passlib[bcrypt]
