"""initial schema fixed order

Revision ID: 2cc20c84d1d5
Revises: 
Create Date: 2025-12-13 00:40:15.010687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc20c84d1d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create base tables first (no dependencies)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    
    op.create_table('prisoner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpid', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('facility', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('safety_classification', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpid')
    )
    op.create_index(op.f('ix_prisoner_id'), 'prisoner', ['id'], unique=False)

    # 2. Create letter table (depends on user, prisoner) WITHOUT circular FK to letterversion
    op.create_table('letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prisoner_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('intake_source', sa.String(length=100), nullable=True),
    sa.Column('original_file_path', sa.String(length=255), nullable=True),
    sa.Column('redacted_file_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('intake', 'scanned', 'redacted', 'reviewed', 'assigned', 'response_started', 'sponsor_submitted', 'revisions_requested', 'approved', 'archived', name='letterstatus'), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('content_format', sa.Enum('markdown', 'html', 'plaintext', name='contentformat'), nullable=False),
    sa.Column('latest_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prisoner_id'], ['prisoner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prisoner_id', 'id', name='uq_letter_prisoner_id')
    )
    op.create_index(op.f('ix_letter_id'), 'letter', ['id'], unique=False)
    print('Created user, prisoner, letter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissionstatushistory')
    op.drop_table('submissionartifact')
    op.drop_table('sponsorprisoner')
    op.drop_table('redactionevent')
    op.drop_table('ocrartifact')
    op.drop_table('letterdates')
    op.drop_index(op.f('ix_envelopejob_batch_id'), table_name='envelopejob')
    op.drop_table('envelopejob')
    op.drop_table('auditlog')
    op.drop_table('assignment')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('submissionversion')
    op.drop_table('submission')
    op.drop_index(op.f('ix_prisoner_id'), table_name='prisoner')
    op.drop_table('prisoner')
    op.drop_table('letterversion')
    op.drop_index(op.f('ix_letter_id'), table_name='letter')
    op.drop_table('letter')
    # ### end Alembic commands ###
